---
title: glossboss.de - Der Autopflege Blog für echte Enthusiasten
email: mail@glossboss.de
description: Ein Autopflegeblog von und für absolute Enthusiasten
baseurl: ''
url: https://glossboss.de
max_index_posts: 15
exclude:
- ".htaccess"
- Gemfile
- Gemfile.lock
- _sass
- node_modules
- Gruntfile.js
- gulpfile.babel.js
- .babel.rc
- package.json
- js
- css
- Gulpfile.js
- rakefile
- script
- postDB
- task
- kontakt
include:
- dist
- images
- was-wird-gespeichert
markdown: redcarpet
permalink: "/:categories/:title/"
version: 20
postversion: 59
headimggradient: linear-gradient(HSLA(197, 100%, 49%,.6),HSLA(197, 100%, 49%,1))
collections:
  preview:
    output: true
    permalink: "/preview/:title/"
port: 1338
