---
title: glossboss.de - Der Autopflege Blog für echte Enthusiasten
email: mail@glossboss.de
description: Ein Autopflegeblog von und für absolute Enthusiasten
baseurl: ''
url: https://glossboss.de
max_index_posts: 15
exclude:
- ".htaccess"
- _sass
- config.codekit
- node_modules
- Gruntfile.js
- package.json
- js
- css
- apache_htaccess.txt
- pdf
- 2015-mm-dd-POST.md
- config
- description
- HEAD
- Gulpfile.js
- rakefile
- sftp-config.json
include:
- dist
- images
- was-wird-gespeichert
markdown: kramdown
permalink: "/:categories/:title/"
version: 150
postversion: 27
headimggradient: linear-gradient(HSLA(197, 100%, 49%,.6),HSLA(197, 100%, 49%,1))
collections:
  preview:
    output: true
    permalink: "/preview/:title/"
port: 1338
