---
title: glossboss.de - Der Autopflege Blog für echte Enthusiasten
email: mail@glossboss.de
description: Ein Autopflegeblog von und für absolute Enthusiasten
baseurl: ''
url: https://glossboss.de
max_index_posts: 10
exclude:
- ".htaccess"
- _sass
- config.codekit
- node_modules
- Gruntfile.js
- package.json
- js
- css
- apache_htaccess.txt
- pdf
- 2015-mm-dd-POST.md
- config
- description
- HEAD
- rakefile
- sftp-config.json
include:
- images
- was-wird-gespeichert
markdown: kramdown
permalink: "/:categories/:title"
cssjsversion: 88
livebuild: true
headimggradient: linear-gradient(HSLA(197, 100%, 49%,.6),HSLA(197, 100%, 49%,.9))
collections:
  preview:
    output: true
    permalink: "/preview/:path/"
port: 1337
