backend:
  name: github
  repo: ntwcklng/gb
  branch: cms
public_folder: "images/uploads"
media_folder: "images/uploads"
collections:
  - name: "produkttest"
    label: "Produkttest"
    folder: "produkttest/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Layout", name: 'layout', widget: "string", default: 'post'}
      - {label: "Title", name: 'title', widget: "string"}
      - {label: "SubTitle", name: 'subtitle', widget: "string"}
      - {label: "Author", name: 'author', widget: "string"}
      - {label: "Header Image", name: 'header_image', widget: "string"}
      - {label: "Content", name: 'body', widget: "markdown"}